<?php

namespace ContainerTGK9OU6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1BnMasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K1BnMas' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K1BnMas'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\AdministrationController::configureUserMenu' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\PresentationsController::index' => ['privates', '.service_locator..lXNT0X', 'get_ServiceLocator__LXNT0XService', true],
            'App\\Controller\\PrestationsController::index' => ['privates', '.service_locator.qrx1RH3', 'get_ServiceLocator_Qrx1RH3Service', true],
            'App\\Controller\\ProductsController::index' => ['privates', '.service_locator.5_j.JOr', 'get_ServiceLocator_5J_JOrService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.QaaDzHL', 'get_ServiceLocator_QaaDzHLService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AdministrationController:configureUserMenu' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\PresentationsController:index' => ['privates', '.service_locator..lXNT0X', 'get_ServiceLocator__LXNT0XService', true],
            'App\\Controller\\PrestationsController:index' => ['privates', '.service_locator.qrx1RH3', 'get_ServiceLocator_Qrx1RH3Service', true],
            'App\\Controller\\ProductsController:index' => ['privates', '.service_locator.5_j.JOr', 'get_ServiceLocator_5J_JOrService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.QaaDzHL', 'get_ServiceLocator_QaaDzHLService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AdministrationController::configureUserMenu' => '?',
            'App\\Controller\\PresentationsController::index' => '?',
            'App\\Controller\\PrestationsController::index' => '?',
            'App\\Controller\\ProductsController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AdministrationController:configureUserMenu' => '?',
            'App\\Controller\\PresentationsController:index' => '?',
            'App\\Controller\\PrestationsController:index' => '?',
            'App\\Controller\\ProductsController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
