<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container99nEORl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container99nEORl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container99nEORl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container99nEORl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container99nEORl\App_KernelDevDebugContainer([
    'container.build_hash' => '99nEORl',
    'container.build_id' => '8e25a1fe',
    'container.build_time' => 1697008061,
], __DIR__.\DIRECTORY_SEPARATOR.'Container99nEORl');
