<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyrhC63\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyrhC63/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNyrhC63.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNyrhC63\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNyrhC63\App_KernelDevDebugContainer([
    'container.build_hash' => 'NyrhC63',
    'container.build_id' => 'ccf5c806',
    'container.build_time' => 1697699599,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNyrhC63');
