<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGVkNYL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGVkNYL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZGVkNYL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZGVkNYL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZGVkNYL\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZGVkNYL',
    'container.build_id' => 'b1127da9',
    'container.build_time' => 1697209102,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGVkNYL');
