<?php

namespace ContainerGyhNfxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__LXNT0XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..lXNT0X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..lXNT0X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manage' => ['privates', 'App\\Repository\\PresentationRepository', 'getPresentationRepositoryService', true],
        ], [
            'manage' => 'App\\Repository\\PresentationRepository',
        ]);
    }
}
