<?php

namespace ContainerZbKeum9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3vZLzvEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.3vZLzvE' shared service.
     *
     * @return \App\Controller\AvisRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\PageAvisController::index()": the $avis argument is type-hinted with the non-existent class or interface: "App\\Controller\\AvisRepository". Did you forget to add a use statement?');
    }
}
