<?php

namespace ContainerZbKeum9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9dAc5AZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9dAc5AZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9dAc5AZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avis' => ['privates', '.errored.3vZLzvE', NULL, 'Cannot determine controller argument for "App\\Controller\\PageAvisController::index()": the $avis argument is type-hinted with the non-existent class or interface: "App\\Controller\\AvisRepository". Did you forget to add a use statement?'],
        ], [
            'avis' => '?',
        ]);
    }
}
