<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEJorivN\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEJorivN/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEJorivN.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEJorivN\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerEJorivN\App_KernelProdContainer([
    'container.build_hash' => 'EJorivN',
    'container.build_id' => 'f7e6bf24',
    'container.build_time' => 1697388054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEJorivN');
