<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Presentation extends \App\Entity\Presentation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'autre' => [parent::class, 'autre', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'expertise' => [parent::class, 'expertise', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'intituleAutre' => [parent::class, 'intituleAutre', null],
        "\0".parent::class."\0".'intituleDescription' => [parent::class, 'intituleDescription', null],
        "\0".parent::class."\0".'intituleExpertise' => [parent::class, 'intituleExpertise', null],
        'autre' => [parent::class, 'autre', null],
        'description' => [parent::class, 'description', null],
        'expertise' => [parent::class, 'expertise', null],
        'id' => [parent::class, 'id', null],
        'intituleAutre' => [parent::class, 'intituleAutre', null],
        'intituleDescription' => [parent::class, 'intituleDescription', null],
        'intituleExpertise' => [parent::class, 'intituleExpertise', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
